In [1]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [40]:
data=pd.read_excel('excel_data.xlsx',index_col='id')

In [41]:
data.head(5)

,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
id,,,,,,,,,,,,,,,,
1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 151 entries, 1 to 151
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   num                151 non-null    int64
 1   name               151 non-null    object
 2   img                151 non-null    object
 3   type               151 non-null    object
 4   height             151 non-null    object
 5   weight             151 non-null    object
 6   candy              151 non-null    object
 7   candy_count        70 non-null     float64
 8   egg                151 non-null    object
 9   spawn_chance       151 non-null    float64
 10  avg_spawns         151 non-null    float64
 11  spawn_time         145 non-null    object
 12  multipliers        70 non-null     object
 13  weaknesses         151 non-null    object
 14  next_evolution     70 non-null     object
 15  prev_evolution     72 non-null     object
 16  num_of_weaknesses  151 non-null    int64
 17  weaknesses_new     151 non-null    object
dtypes: float64(3), int64(2), object(13)
memory usage: 22.4+ KB

In [54]:
data.isnull().sum()

num                   0
name                  0
img                   0
type                  0
height                0
weight                0
candy                 0
candy_count          81
egg                   0
spawn_chance          0
avg_spawns            0
spawn_time            6
multipliers          81
weaknesses            0
next_evolution       81
prev_evolution       79
num_of_weaknesses     0
weaknesses_new        0
dtype: int64

In [8]:
data.type.unique()

array(["['Grass', 'Poison']", "['Fire']", "['Fire', 'Flying']",
       "['Water']", "['Bug']", "['Bug', 'Flying']", "['Bug', 'Poison']",
       "['Normal', 'Flying']", "['Normal']", "['Poison']", "['Electric']",
       "['Ground']", "['Poison', 'Ground']", "['Poison', 'Flying']",
       "['Bug', 'Grass']", "['Fighting']", "['Water', 'Fighting']",
       "['Psychic']", "['Water', 'Poison']", "['Rock', 'Ground']",
       "['Water', 'Psychic']", "['Water', 'Ice']", "['Ghost', 'Poison']",
       "['Grass', 'Psychic']", "['Ground', 'Rock']", "['Grass']",
       "['Ice', 'Psychic']", "['Water', 'Flying']", "['Rock', 'Water']",
       "['Rock', 'Flying']", "['Ice', 'Flying']",
       "['Electric', 'Flying']", "['Dragon']", "['Dragon', 'Flying']"],
      dtype=object)

In [11]:
data.next_evolution[1]

"[{'num': '002', 'name': 'Ivysaur'}, {'num': '003', 'name': 'Venusaur'}]"

## # Get all Pokemons whose spawn rate is less than 5%

In [15]:
data[data.spawn_chance<0.05]

,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
id,,,,,,,,,,,,,,,,
2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"['Fire', 'Flying']",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"['Water', 'Electric', 'Rock']",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
8,8,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,['Water'],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"['Electric', 'Grass']","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Water', 'Electric', 'Rock']",NaN,NaN
148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN
151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN

In [51]:
print(list(data.name[data.spawn_chance<0.05]),end=',')

['Ivysaur', 'Venusaur', 'Charmeleon', 'Charizard', 'Wartortle', 'Blastoise', 'Butterfree', 'Raichu', 'Sandslash', 'Nidoqueen', 'Nidoking', 'Clefable', 'Ninetales', 'Wigglytuff', 'Vileplume', 'Dugtrio', 'Persian', 'Primeape', 'Arcanine', 'Poliwrath', 'Kadabra', 'Alakazam', 'Machoke', 'Machamp', 'Victreebel', 'Golem', 'Rapidash', 'Slowbro', 'Magneton', "Farfetch'd", 'Dewgong', 'Muk', 'Cloyster', 'Gengar', 'Electrode', 'Exeggutor', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Weezing', 'Rhydon', 'Chansey', 'Kangaskhan', 'Seadra', 'Starmie', 'Mr. Mime', 'Gyarados', 'Lapras', 'Ditto', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omastar', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dragonair', 'Dragonite', 'Mewtwo', 'Mew'],

#### from above we can see that there total of 65 pokemons that has spawn_rate less that 5 %

##  Get all Pokemons that have less than 4 weaknesses

In [22]:
[i for i in data.weaknesses]

["['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Water', 'Ground', 'Rock']",
 "['Water', 'Ground', 'Rock']",
 "['Water', 'Electric', 'Rock']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Fire', 'Flying', 'Rock']",
 "['Fire', 'Flying', 'Rock']",
 "['Fire', 'Electric', 'Ice', 'Flying', 'Rock']",
 "['Fire', 'Flying', 'Psychic', 'Rock']",
 "['Fire', 'Flying', 'Psychic', 'Rock']",
 "['Fire', 'Flying', 'Psychic', 'Rock']",
 "['Electric', 'Rock']",
 "['Electric', 'Rock']",
 "['Electric', 'Rock']",
 "['Fighting']",
 "['Fighting']",
 "['Electric', 'Rock']",
 "['Electric', 'Rock']",
 "['Ground', 'Psychic']",
 "['Ground', 'Psychic']",
 "['Ground']",
 "['Ground']",
 "['Water', 'Grass', 'Ice']",
 "['Water', 'Grass', 'Ice']",
 "['Ground', 'Psychic']",
 "['Ground', 'Psychic']",
 "['Water', 'Ice', 'Ground', 'Psychic']",
 "['Ground', 'Psychic']",
 "['Ground', 'Psychic']",
 "['Water', 'Ice', 'Ground', 'Psychic']",
 "['Fighting']",
 "['Fighting']",
 "['Water', 'Ground', 'Rock']",
 "['Water', 'Ground', 'Rock']",
 "['Fighting']",
 "['Fighting']",
 "['Electric', 'Ice', 'Psychic', 'Rock']",
 "['Electric', 'Ice', 'Psychic', 'Rock']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Fire', 'Ice', 'Poison', 'Flying', 'Bug', 'Rock']",
 "['Fire', 'Ice', 'Poison', 'Flying', 'Bug', 'Rock']",
 "['Fire', 'Flying', 'Psychic', 'Rock']",
 "['Fire', 'Flying', 'Psychic', 'Rock']",
 "['Water', 'Grass', 'Ice']",
 "['Water', 'Grass', 'Ice']",
 "['Fighting']",
 "['Fighting']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Flying', 'Psychic', 'Fairy']",
 "['Flying', 'Psychic', 'Fairy']",
 "['Water', 'Ground', 'Rock']",
 "['Water', 'Ground', 'Rock']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass', 'Flying', 'Psychic', 'Fairy']",
 "['Bug', 'Ghost', 'Dark']",
 "['Bug', 'Ghost', 'Dark']",
 "['Bug', 'Ghost', 'Dark']",
 "['Flying', 'Psychic', 'Fairy']",
 "['Flying', 'Psychic', 'Fairy']",
 "['Flying', 'Psychic', 'Fairy']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Fire', 'Ice', 'Flying', 'Psychic']",
 "['Electric', 'Ground', 'Psychic']",
 "['Electric', 'Ground', 'Psychic']",
 "['Water', 'Grass', 'Ice', 'Fighting', 'Ground', 'Steel']",
 "['Water', 'Grass', 'Ice', 'Fighting', 'Ground', 'Steel']",
 "['Water', 'Grass', 'Ice', 'Fighting', 'Ground', 'Steel']",
 "['Water', 'Ground', 'Rock']",
 "['Water', 'Ground', 'Rock']",
 "['Electric', 'Grass', 'Bug', 'Ghost', 'Dark']",
 "['Electric', 'Grass', 'Bug', 'Ghost', 'Dark']",
 "['Fire', 'Water', 'Ground']",
 "['Fire', 'Water', 'Ground']",
 "['Electric', 'Rock']",
 "['Electric', 'Rock']",
 "['Electric', 'Rock']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass', 'Fighting', 'Rock']",
 "['Ground', 'Psychic']",
 "['Ground', 'Psychic']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass', 'Fighting', 'Rock']",
 "['Ground', 'Psychic', 'Ghost', 'Dark']",
 "['Ground', 'Psychic', 'Ghost', 'Dark']",
 "['Ground', 'Psychic', 'Ghost', 'Dark']",
 "['Water', 'Grass', 'Ice', 'Fighting', 'Ground', 'Steel']",
 "['Bug', 'Ghost', 'Dark']",
 "['Bug', 'Ghost', 'Dark']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Ground']",
 "['Ground']",
 "['Fire', 'Ice', 'Poison', 'Flying', 'Bug', 'Ghost', 'Dark']",
 "['Fire', 'Ice', 'Poison', 'Flying', 'Bug', 'Ghost', 'Dark']",
 "['Water', 'Grass', 'Ice']",
 "['Water', 'Grass', 'Ice']",
 "['Flying', 'Psychic', 'Fairy']",
 "['Flying', 'Psychic', 'Fairy']",
 "['Fighting']",
 "['Ground', 'Psychic']",
 "['Ground', 'Psychic']",
 "['Water', 'Grass', 'Ice', 'Fighting', 'Ground', 'Steel']",
 "['Water', 'Grass', 'Ice', 'Fighting', 'Ground', 'Steel']",
 "['Fighting']",
 "['Fire', 'Ice', 'Poison', 'Flying', 'Bug']",
 "['Fighting']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass']",
 "['Electric', 'Grass', 'Bug', 'Ghost', 'Dark']",
 "['Bug', 'Ghost', 'Dark']",
 "['Fire', 'Electric', 'Ice', 'Flying', 'Rock']",
 "['Fire', 'Bug', 'Rock', 'Ghost', 'Dark', 'Steel']",
 "['Ground']",
 "['Water', 'Ground', 'Rock']",
 "['Fire', 'Flying', 'Rock']",
 "['Fighting']",
 "['Electric', 'Grass']",
 "['Electric', 'Rock']",
 "['Electric', 'Grass', 'Fighting', 'Rock']",
 "['Fighting']",
 "['Fighting']",
 "['Electric', 'Grass']",
 "['Ground']",
 "['Water', 'Ground', 'Rock']",
 "['Fighting']",
 "['Electric', 'Grass', 'Fighting', 'Ground']",
 "['Electric', 'Grass', 'Fighting', 'Ground']",
 "['Electric', 'Grass', 'Fighting', 'Ground']",
 "['Electric', 'Grass', 'Fighting', 'Ground']",
 "['Water', 'Electric', 'Ice', 'Rock', 'Steel']",
 "['Fighting']",
 "['Fire', 'Electric', 'Rock', 'Steel']",
 "['Ice', 'Rock']",
 "['Water', 'Electric', 'Rock']",
 "['Ice', 'Dragon', 'Fairy']",
 "['Ice', 'Dragon', 'Fairy']",
 "['Ice', 'Rock', 'Dragon', 'Fairy']",
 "['Bug', 'Ghost', 'Dark']",
 "['Bug', 'Ghost', 'Dark']"]

In [33]:
num_of_weaknesses=[]
weaknesses_new=[]
for i in data.weaknesses:
    exec('x='+i)
    weaknesses_new.append(x)
    num_of_weaknesses.append(len(x))

In [42]:
data['num_of_weaknesses']=num_of_weaknesses
data['weaknesses_new']=weaknesses_new

In [50]:
data[data.num_of_weaknesses<4]

,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,num_of_weaknesses,weaknesses_new
id,,,,,,,,,,,,,,,,,,
4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,3,"[Water, Ground, Rock]"
5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",3,"[Water, Ground, Rock]"
6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"['Fire', 'Flying']",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"['Water', 'Electric', 'Rock']",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':...",3,"[Water, Electric, Rock]"
7,7,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,['Water'],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"['Electric', 'Grass']","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN,2,"[Electric, Grass]"
8,8,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,['Water'],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"['Electric', 'Grass']","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]",2,"[Electric, Grass]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Water', 'Electric', 'Rock']",NaN,NaN,3,"[Water, Electric, Rock]"
147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","['Ice', 'Dragon', 'Fairy']","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,3,"[Ice, Dragon, Fairy]"
148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",3,"[Ice, Dragon, Fairy]"
150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN,3,"[Bug, Ghost, Dark]"
151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN,3,"[Bug, Ghost, Dark]"

In [48]:
# all Pokemons that have less than 4 weaknesses
print(list(data.name[data.num_of_weaknesses<4]),end=',')

['Charmander', 'Charmeleon', 'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Pidgey', 'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran ♀ (Female)', 'Nidorina', 'Nidoran ♂ (Male)', 'Nidorino', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl', 'Abra', 'Kadabra', 'Alakazam', 'Machop', 'Machoke', 'Machamp', 'Tentacool', 'Tentacruel', 'Ponyta', 'Rapidash', 'Magnemite', 'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Grimer', 'Muk', 'Shellder', 'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Koffing', 'Weezing', 'Chansey', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Mr. Mime', 'Electabuzz', 'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Snorlax', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair', 'Mewtwo', 'Mew'],

#### From above we can conclude that there are 102 pokemons who has less than 4 weeknesses

## Get all Pokemons that have no multipliers at all

In [60]:
print(list(data.name[data.multipliers.isnull()]),end=',')
print('\n',len(data[data.multipliers.isnull()]))

['Venusaur', 'Charizard', 'Blastoise', 'Butterfree', 'Beedrill', 'Pidgeot', 'Raticate', 'Fearow', 'Arbok', 'Raichu', 'Sandslash', 'Nidoqueen', 'Nidoking', 'Clefable', 'Ninetales', 'Wigglytuff', 'Golbat', 'Vileplume', 'Parasect', 'Venomoth', 'Dugtrio', 'Persian', 'Golduck', 'Primeape', 'Arcanine', 'Poliwrath', 'Alakazam', 'Machamp', 'Victreebel', 'Tentacruel', 'Golem', 'Rapidash', 'Slowbro', 'Magneton', "Farfetch'd", 'Dodrio', 'Dewgong', 'Muk', 'Cloyster', 'Gengar', 'Onix', 'Hypno', 'Kingler', 'Electrode', 'Exeggutor', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Weezing', 'Rhydon', 'Chansey', 'Tangela', 'Kangaskhan', 'Seadra', 'Seaking', 'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir', 'Tauros', 'Gyarados', 'Lapras', 'Ditto', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omastar', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dragonite', 'Mewtwo', 'Mew'],
 81

#### From above we can conclude that there are 81 pokemons who has zero multipliers

## Get all Pokemons that do not have more than 2 evolutions

#### as each evolution is considered as different entity we will consider next_evolution to solve this question

In [66]:
data.next_evolution.fillna('[]',inplace=True)
data.next_evolution

id
1      [{'num': '002', 'name': 'Ivysaur'}, {'num': '0...
2                   [{'num': '003', 'name': 'Venusaur'}]
3                                                     []
4      [{'num': '005', 'name': 'Charmeleon'}, {'num':...
5                  [{'num': '006', 'name': 'Charizard'}]
                             ...
147    [{'num': '148', 'name': 'Dragonair'}, {'num': ...
148                [{'num': '149', 'name': 'Dragonite'}]
149                                                   []
150                                                   []
151                                                   []
Name: next_evolution, Length: 151, dtype: object

In [67]:
num_of_next_evolution=[]
next_evolution_new=[]
for i in data.next_evolution:
    exec('x='+i)
    next_evolution_new.append(x)
    num_of_next_evolution.append(len(x))

data['num_of_next_evolution']=num_of_next_evolution
data['next_evolution_new']=next_evolution_new

In [69]:
print(list(data.name[data.num_of_next_evolution<2]),end=',')
print('\n',len(list(data.name[data.num_of_next_evolution<2])))

['Ivysaur', 'Venusaur', 'Charmeleon', 'Charizard', 'Wartortle', 'Blastoise', 'Metapod', 'Butterfree', 'Kakuna', 'Beedrill', 'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidorina', 'Nidoqueen', 'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Poliwhirl', 'Poliwrath', 'Kadabra', 'Alakazam', 'Machoke', 'Machamp', 'Weepinbell', 'Victreebel', 'Tentacool', 'Tentacruel', 'Graveler', 'Golem', 'Ponyta', 'Rapidash', 'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Haunter', 'Gengar', 'Onix', 'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute', 'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey', 'Tangela', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras', 'Ditto', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dragonair', 'Dragonite', 'Mewtwo', 'Mew'],
 134

#### From above we can conclude that there are 134 pokemons who has less than 2 evolution

In [72]:
data.drop(['weaknesses','next_evolution'],axis=1,inplace=True)
data

,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,prev_evolution,num_of_weaknesses,weaknesses_new,num_of_next_evolution,next_evolution_new
id,,,,,,,,,,,,,,,,,,
1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],NaN,4,"[Fire, Ice, Flying, Psychic]",2,"[{'num': '002', 'name': 'Ivysaur'}, {'num': '0..."
2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[{'num': '001', 'name': 'Bulbasaur'}]",4,"[Fire, Ice, Flying, Psychic]",1,"[{'num': '003', 'name': 'Venusaur'}]"
3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",4,"[Fire, Ice, Flying, Psychic]",0,[]
4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],NaN,3,"[Water, Ground, Rock]",2,"[{'num': '005', 'name': 'Charmeleon'}, {'num':..."
5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[{'num': '004', 'name': 'Charmander'}]",3,"[Water, Ground, Rock]",1,"[{'num': '006', 'name': 'Charizard'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]",NaN,3,"[Ice, Dragon, Fairy]",2,"[{'num': '148', 'name': 'Dragonair'}, {'num': ..."
148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[{'num': '147', 'name': 'Dratini'}]",3,"[Ice, Dragon, Fairy]",1,"[{'num': '149', 'name': 'Dragonite'}]"
149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",4,"[Ice, Rock, Dragon, Fairy]",0,[]
150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,NaN,3,"[Bug, Ghost, Dark]",0,[]
151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,NaN,3,"[Bug, Ghost, Dark]",0,[]

## Get all Pokemons whose spawn time is less than 300 seconds.

In [75]:
data.spawn_time.fillna('00:00',inplace=True)
data.spawn_time

id
1      20:00
2      07:00
3      11:30
4      08:45
5      19:00
       ...
147    06:41
148    11:57
149    23:38
150    00:00
151    00:00
Name: spawn_time, Length: 151, dtype: object

In [86]:
spawn_time_sec=[]
for i in data.spawn_time:
    x=int(i[:2])*60+int(i[3:])
    spawn_time_sec.append(x)

data['spawn_time_sec']=spawn_time_sec

In [87]:
print(list(data.name[data.spawn_time_sec<300]),end=',')
print('\n',len(list(data.name[data.spawn_time_sec<300])))

['Squirtle', 'Blastoise', 'Metapod', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Fearow', 'Arbok', 'Pikachu', 'Sandshrew', 'Nidoran ♀ (Female)', 'Nidoran ♂ (Male)', 'Clefairy', 'Clefable', 'Ninetales', 'Golbat', 'Oddish', 'Paras', 'Parasect', 'Venonat', 'Diglett', 'Meowth', 'Persian', 'Psyduck', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwrath', 'Abra', 'Machop', 'Machamp', 'Bellsprout', 'Tentacool', 'Graveler', 'Ponyta', 'Rapidash', 'Slowbro', 'Magnemite', "Farfetch'd", 'Dodrio', 'Muk', 'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix', 'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Cubone', 'Marowak', 'Hitmonlee', 'Lickitung', 'Rhyhorn', 'Chansey', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Mr. Mime', 'Electabuzz', 'Pinsir', 'Tauros', 'Gyarados', 'Ditto', 'Jolteon', 'Porygon', 'Kabuto', 'Articuno', 'Zapdos', 'Moltres', 'Mewtwo', 'Mew'],
 81

#### From above we can conclude that there are 81 pokemons who has less than 300 sec span time

## Get all Pokemon who have more than two types of capabilities

In [89]:
num_of_type=[]
type_new=[]
for i in data.type:
    exec('x='+i)
    type_new.append(x)
    num_of_type.append(len(x))

data['num_of_type']=num_of_type
data['type_new']=type_new

In [90]:
print(list(data.name[data.num_of_type<2]),end=',')
print('\n',len(list(data.name[data.num_of_type<2])))

['Charmander', 'Charmeleon', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Rattata', 'Raticate', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran ♀ (Female)', 'Nidorina', 'Nidoran ♂ (Male)', 'Nidorino', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl', 'Abra', 'Kadabra', 'Alakazam', 'Machop', 'Machoke', 'Machamp', 'Ponyta', 'Rapidash', 'Magnemite', 'Magneton', 'Seel', 'Grimer', 'Muk', 'Shellder', 'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Koffing', 'Weezing', 'Chansey', 'Tangela', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Mr. Mime', 'Electabuzz', 'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Snorlax', 'Dratini', 'Dragonair', 'Mewtwo', 'Mew'],
 89

#### From above we can conclude that there are 89 pokemons who has less than 2 types of capabilities

In [91]:
data.to_csv('pokemon_data.csv')